name: Publish

on:
  release:
    types: [published]

jobs:
  packages:
    runs-on: ubuntu-latest
    services:
      yarn-image:
        image: doutorspace/yarn:latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x

      - uses: actions/checkout@v1

      - name: Install
        run: yarn install --silent

      - name: Build
        run: yarn build

      - name: Configure NPMJS Token
        run: npm set registry https://registry.npmjs.org/ && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
