name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      yarn-image:
        image: doutorspace/yarn:latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.x"
      - uses: actions/checkout@v1

      - name: Install, Lint, Test and Build for Test
        run: |
          yarn install --silent
          yarn lint
          yarn test
          yarn build
